services:
  app:
    build: .
    volumes:
      - ..:/workspace:cached
    command: sleep infinity
    networks:
      - devnet
    depends_on:
      - db

  db:
    image: postgres:17
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - devnet

networks:
  devnet:

volumes:
  postgres_data: